# Generated by Django 3.2.9 on 2022-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'verbose_name': 'Over Time', 'verbose_name_plural': 'Over Time'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_CEO',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_reg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='no_of_employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='no_of_staff',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='office_number',
            field=models.CharField(default=233567890, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default=4567890987, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
