# Generated by Django 3.2.9 on 2022-04-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
    ]
