# Generated by Django 3.2.9 on 2022-04-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20220401_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(default='John Doe', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(default=4567890, max_length=30),
            preserve_default=False,
        ),
    ]
