# Generated by Django 3.2.9 on 2022-04-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_remove_employee_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeReg_Id',
            field=models.CharField(max_length=200),
        ),
    ]
