# Generated by Django 3.2.9 on 2022-04-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_employee_employeereg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime',
            old_name='employee',
            new_name='my_employee',
        ),
    ]
