# Generated by Django 4.0.3 on 2022-04-19 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtime', '0003_rename_employoer_requestedovertimes_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedovertimes',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
