# Generated by Django 3.2.9 on 2022-04-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_rename_employee_overtime_my_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overtime',
        ),
    ]
