# Generated by Django 3.2.9 on 2022-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_alter_employee_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=123456789, max_length=40),
            preserve_default=False,
        ),
    ]
