# Generated by Django 3.2.9 on 2022-04-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
