# Generated by Django 3.2.9 on 2022-04-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
