# Generated by Django 4.0.3 on 2022-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0011_overtime_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
