# Generated by Django 4.0.3 on 2022-04-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0012_alter_overtime_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='approved_by',
        ),
    ]
