# Generated by Django 4.0.3 on 2022-04-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtime', '0014_overtime_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Hr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
